sudo: required
services:
  - docker
before_install:
  - docker build -t suneel4b5/kvs -f Dockerfile.dev .
script:
  - docker run -e CI=true suneel4b5/kvs npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "KVS"
  env: "Kvs-env"
  bucket_name: "elasticbeanstalk-us-east-2-314292627665"
  bucket_path: "KVS"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY