version: '3.9'
services:
  kvs-shop:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - /app/node_modules
      - "D:/coding/React app/kvs-shop:/app"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - "D:/coding/React app/kvs-shop:/app"
    command: ["npm", "run", "test"]